import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next JS App",
  description: "Generated by Safi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`antialiased text-sm`}
      >
        {children}
      </body>
    </html>
  );
}
